#@data/values
domain: lab.shortrib.net
windows:
    image: https://software-download.microsoft.com/download/pr/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso
    checksum: 3022424f777b66a698047ba1c37812026b9714c5
template_name: outsystems-image
default_password: ENC[AES256_GCM,data:MfJ0swEn60zir045xAIsIYOwadB2v6g=,iv:7pLc/EjamtPXlxm5wXjLDlvz2jXYH67EwopyZXCyTpw=,tag:2he1D9DYBIZzoBKV6kDJLA==,type:str]
server:
    cpus: 2
    memory: 4096
    disk: 102400
vsphere:
    server: vcenter.lab.shortrib.net
    username: terraform
    password: ENC[AES256_GCM,data:RU+M1x/UB2fo7TaHOLlZi0UHjbo=,iv:72eQ77PNWql1dt8JzauBcbSCDS4BBSvOehBNzF92hco=,tag:Bdnm0rx1v4jj3vQS/O6uzg==,type:str]
    datacenter: garage
    cluster: homelab
    host: rye.lab.shortrib.net
    resource_pool: homelab/Resources
    network: management-pg
    datastore: vsanDatastore
    folder: infrastructure
gcp:
    project: shortrib
bucket: images
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-23T19:32:31Z"
    mac: ENC[AES256_GCM,data:/yEmPhu91Hr0x5Irm4VOLeK2jEMZS2ydIYRd3+w3YyE4YMydBLas1Ze2pB7ahVjGPM3Kr0j3TP72eK5CqMtRPZ2EBvuSLN0coi1w7NayxJISJhkl1afYyebMTbA3z6fLttQknR3pYNWDbwl0hi0nFqsgO+KGJIYarRbNi0gTxNM=,iv:iGkH5nv6Hi9wZ9dP5uFusLn9U4MbBmfaNHA1W5HbzLk=,tag:dTJfAWEaSLrpeLxIu3n1Fg==,type:str]
    pgp:
        - created_at: "2024-01-23T19:32:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAR67fubJFgeSkrcU6ZQn0NPggA2ogjm3+848fNqadpksw
            /lJl9apxKVeY1gSNreXKdFDhupzK8k6t7teAugQRmikeNQlGkZyvIVTM6hjraQUJ
            0lwBu16fG3t+V5i4V82VSjWPwAaKfQYDluBAqaXwRPqeFFpoXDSivYqAU3dp1jcu
            s162/5tH9X0AdvJCAMbK9k4VaICX2Olr20Nvd1t2PDXIHnlSNBG3rhgFtz6Xyw==
            =PlSW
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password)$
    version: 3.7.3
